using CairoMakie

hfile = h5open(data_directory  * "/structured_eigenvalues_and_generators.hdf5", "r")
Λ_bskmeans = read(hfile["Λ_bskmeans"])
Λ_unstructured = read(hfile["Λ_unstructured"])
Λ_kmeans = read(hfile["Λ_kmeans"])
Λ_rbf = read(hfile["Λ_rbf"])
Λ_rbf_2 = read(hfile["Λ_rbf_2"])
Λ_rbf_3 = read(hfile["Λ_rbf_3"])
Λ_ulam = read(hfile["Λ_ulam"])
close(hfile)

fig = Figure(resolution = (600, 600))
ax = Axis(fig[1, 1]; title = "K-Means", ylabel = "Imaginary", xlabel = "Real")
bkmeans_indices = reverse(sortperm(abs.(Λ_bskmeans)))[1:2000]
bkm_op = 0.05
scatter!(ax, real.(Λ_bskmeans[bkmeans_indices]), imag.(Λ_bskmeans[bkmeans_indices]), color = (:red, bkm_op))
scatter!(ax, real.(Λ_kmeans), imag.(Λ_kmeans), color = (:blue, 0.5))
xlims!(ax, (-1.1, 1.1))
ylims!(ax, (-1.1, 1.1))
hidexdecorations!(ax; grid = false)
ax = Axis(fig[1, 2]; title = "RBF", ylabel = "Imaginary", xlabel = "Real")
scatter!(ax, real.(Λ_bskmeans[bkmeans_indices]), imag.(Λ_bskmeans[bkmeans_indices]), color = (:red, bkm_op))
scatter!(ax, real.(Λ_rbf_3), imag.(Λ_rbf_3), color = (:blue, 0.5))
xlims!(ax, (-1.1, 1.1))
ylims!(ax, (-1.1, 1.1))
hidexdecorations!(ax; grid = false)
hideydecorations!(ax; grid = false)
ax = Axis(fig[2, 1]; title = "Bisecting K-Means", ylabel = "Imaginary", xlabel = "Real")
scatter!(ax, real.(Λ_bskmeans[bkmeans_indices]), imag.(Λ_bskmeans[bkmeans_indices]), color = (:red, bkm_op))
scatter!(ax, real.(Λ_unstructured), imag.(Λ_unstructured), color = (:blue, 0.5))
xlims!(ax, (-1.1, 1.1))
ylims!(ax, (-1.1, 1.1))
ax = Axis(fig[2, 2]; title = "Ulam", ylabel = "Imaginary", xlabel = "Real")
scatter!(ax, real.(Λ_bskmeans[bkmeans_indices]), imag.(Λ_bskmeans[bkmeans_indices]), color = (:red, bkm_op))
scatter!(ax, real.(Λ_ulam), imag.(Λ_ulam), color = (:blue, 0.5))
xlims!(ax, (-1.1, 1.1))
ylims!(ax, (-1.1, 1.1))
hideydecorations!(ax; grid = false)

save("RevisionFigures/eigenvalues.png", fig)